services:
  adventour:
    image: php:8.2.4-apache
    restart: always
    depends_on: 
      - database
    ports:
      - "8080:80"
    volumes:
      - ./adventour:/var/www/html
    environment:
      MYSQL_HOST: database
      MYSQL_DATABASE: adventour
      MYSQL_USER: admin
      MYSQL_PASSWORD: password1234
    command: ["apache2-foreground"]

  database:
    image: mysql:8.0.32
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: adventour
      MYSQL_USER: admin
      MYSQL_PASSWORD: password1234
      MYSQL_ROOT_PASSWORD: password1234

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - database
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password1234

volumes:
  mysql:

